config/routes.rb
Rails.application.routes.draw do
  get 'memos/index'

  get 'memos/new'

  get 'memos/create'

  get 'memos/edit'

  get 'memos/update'

  get 'memos/destroy'

  root "home#index"
  
  devise_for :users
  resources :memos
  get 'home/index'

end

app/models/memo.rb
class Memo < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  def index
  end

  def new
   @memo = Memo.new
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_header.html.erb
 <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- 메모 앱을 누르면 홈으로 가게 만듦-->
    <%=link_to 'Memo App', root_path, id: 'logo'%>
    <nav>
      <!-- 아래는 상단바 메뉴-->
      <ul class="nav navbar-nav navbar-right">
        <li><%=link_to 'Home', root_path %></li>
        <li><%=link_to 'New Memo', memos_new_path %></li>
        <%if user_signed_in?%>
          <li><%=link_to 'Logout', destroy_user_session_path, method: 'delete'%></li>
        <%else%>
          <li><%=link_to 'Sign in', new_user_session_path%></li>
          <li><%=link_to 'Sign up', new_user_registration_path%></li>
        <%end%>
      </ul>
    </nav>
  </div>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
  <body>
    <!-- header를 불러오는 코드 -->
    <%=render'layouts/header'%>
    
    <!-- body 부분 양 옆 간격 주기 how? header와 마찬가지로 container 안에 넣어서! -->
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/memos/create.html.erb
<h1>Memos#create</h1>
<p>Find me in app/views/memos/create.html.erb</p>

app/views/memos/destroy.html.erb
<h1>Memos#destroy</h1>
<p>Find me in app/views/memos/destroy.html.erb</p>

app/views/memos/edit.html.erb
<h1>Memos#edit</h1>
<p>Find me in app/views/memos/edit.html.erb</p>

app/views/memos/index.html.erb
<h1>Memos#index</h1>
<p>Find me in app/views/memos/index.html.erb</p>

app/views/memos/new.html.erb
<%=form_for @memo do |f|%>
    <%=f.text_field :title%><br>
    <%=f.text_area :content%><br>
    <%=f.submit '작성'%>
<%end%>

app/views/memos/update.html.erb
<h1>Memos#update</h1>
<p>Find me in app/views/memos/update.html.erb</p>